# Round 1B (+2E) find/replace items, decoded from training_doc_update_for_claude_code.md
R = [
(1,"If it says System, leave it alone. Moving it yourself can confuse the automation.","If it says System, leave it alone. Moving it yourself can confuse the automation. If a card should have moved and didn't, tell Tim so he can fix it. Want this table on paper? File > Print > Custom pages.",1),
(2,"They asked for a specific day and time to follow up","They asked to be followed up with on a specific day and time",2),
(3,"An attempt every 2 weeks until about day 30","An attempt every 2 weeks until about day 30. Then you get a task to review the card.",1),
(4,"so a card can be in a column and still be marked Lost.","so a card can be in a column and still be marked Lost. To set one, drag the card onto the Lost or Abandoned area. Then add them to win-back by hand: on their contact, go to Actions on the left and scroll down.",1),
(5,"No response after 30 days (the system marks these), or they asked us to stop calling (you mark these)","No longer being worked: no activity after about 30 days (you get a task to review it), or they asked us to stop calling",1),
(6,"Automatic moves and Abandoned","The 30-day review",1),
(7,"Extended Lead after day 14, and Abandoned at about day 30, both happen on their own. The system closes the loop so you never have to decide when to give up on someone.","Extended Lead after day 14 happens on its own. At about day 30 with no activity, you get a task to review the card: Abandoned if they're no longer being worked, Lost if they had a call or consult and didn't convert. Either way, add them to win-back.",1),
(8,"Both Lost and Abandoned go to win-back, an automated email sequence","Both Lost and Abandoned go to win-back (you add them by hand), an automated email sequence",1),
(9,"Someone who asks for a specific day and time gets a check-in right then.","Someone who asks to be followed up with on a specific day and time gets a check-in right then.",1),
(10,"Lock the note in IntakeQ first, then mark Lost and add to win-back","Lock the note in IntakeQ first, drag the card to Lost, then add to win-back (contact > Actions on the left > scroll down)",1),
(11,"Lock the note, mark Abandoned, and add to win-back","Lock the note, drag the card to Abandoned, and add to win-back",1),
(12,"I need to make a superbill","I need to send a superbill",1),
(13,"Mark the opportunity Lost.","Drag the card to Lost.",1),
(14,"Add them to the win-back campaign.","Add them to the win-back campaign: on their contact, Actions on the left, then scroll down.",1),
(15,"Creating a superbill","Sending a superbill",1),
(16,"We'll walk through this one together. Fill it in as you learn it.","Superbills build themselves now. After a client's last visit of the month, their superbill appears automatically in their Files in IntakeQ. We only send them to clients who've asked.",1),
(17,"When does a patient get one?","Who gets one: only clients who've asked (for example, Pamela and Dana). Each one has a monthly reminder task.",1),
(18,"Step 1","Step 1: Open the client's Files in IntakeQ and find the superbill.",1),
(19,"Step 2","Step 2: Click the three dots, then Share to client.",1),
(20,"Step 3","Step 3: Check off the monthly reminder task.",1),
(21,"Step 4","Step 4: A new client asks for superbills? Create a monthly reminder task for them.",1),
(22,"Superbill with Tim.","Sending a superbill.",1),
(23,"Make and send a superbill","Send a superbill to clients who've asked for one",1),
(24,"Superbills: making and sending (fill in Part 5 as you teach it)","Superbills: sending, and monthly reminder tasks for clients who request them",1),
(25,"Office upkeep: stocking bathroom paper goods and soap, WOW packages, trash and liners, cleaning up messes","Office upkeep: stocking bathroom paper goods and soap, trash and liners, cleaning up messes",1),
("2E","When everyone else is busy","When everyone else is busy, or you have downtime",1),
]
